custom:
  project:
    name: battle-royale
  documentation:
    info:
      version: "0.5"
      title: "Battle Royale API"
      description: "This is the API for the currently unnamed Battle Royale IRL app"
      contact:
        name: "Patrick Huynh"
        email: "patrickhuynh97@gmail.com"
    tags:
      - name: "Authorization"
        description: "Endpoints for authorizing a Player or Gamemaster"
      - name: "Player Endpoints"
        description: "Endpoints where the calling user is modelled as a Player"
      - name: "Game Master Endpoints"
        description: "Endpoints where the calling user is modelled as a GameMaster"
    models: ${file(serverless_config/function_documentation/function_documentation.yml)} # todo break this up into smaller files

service:
  name: api-service

provider:
  name: aws
  runtime: ${opt:runtime, 'python3.7'}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  profile: ${opt:profile, 'personal'}
  deploymentBucket:
    name: ${self:custom.project.name}-dev
  versionFunctions: false
  stackTags:
    # Tag all resources that can be tagged e.g. lambdas, DynamoDB tables, ec2, etc.
    SERVICE:  ${self:service.name}
    PROJECT: ${self:custom.project.name}

  iamRoleStatements:
    - Effect: Allow  # God mode lambda
      Action: "*"
      Resource: "*"

functions:
  - ${file(serverless_config/functions/authorization-functions.yml)}
  - ${file(serverless_config/functions/user-functions.yml)}
  - ${file(serverless_config/functions/player-functions.yml)}
  - ${file(serverless_config/functions/game-master-functions.yml)}

package:
  include:
    - 'api/*'
    - 'db/*'
    - 'models/*'
    - 'user_management/*'
    - 'serverless_config/*'
    - 'handlers/*'
  exclude:
    - 'node_modules'
plugins:
  - serverless-python-requirements
  - serverless-aws-documentation
resources:
  - ${file(serverless_config/resources/dynamo-db.yml)}
  - ${file(serverless_config/resources/cognito-user-pool.yml)}
